version: 2
jobs:
  build_py37: &test-template
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.9-stretch
    environment:
      PRE_COMMIT_SKIP=no-commit-to-branch,check-mutable-defaults

    steps:
      - checkout

      - restore_cache:
          key: deps-{{ checksum "poetry.lock" }}

      - run:
          name: install
          command: |
            poetry install -E sqs

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: linters
          command: |
            SKIP=$PRE_COMMIT_SKIP poetry run pre-commit run -a -v

      - run:
          name: tests
          command: |
            make test-cov

      - run:
          name: check-fixtures
          command: |
            make check-fixtures

  build_py38:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster
    environment:
      PRE_COMMIT_SKIP=no-commit-to-branch

  build_py39:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster
    environment:
      PRE_COMMIT_SKIP=no-commit-to-branch


workflows:
  version: 2
  commit:
    jobs:
      - build_py37
      - build_py38
      - build_py39

  scheduled:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: main

    jobs:
      - build_py37
      - build_py38
      - build_py39
