name: Tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "examples/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Hatch
        run: pipx install hatch

      - name: Run static analysis
        run: hatch fmt --check

      - name: Run tests
        run: |
          hatch test -i py=${{ matrix.python-version }}

      - name: Run type checks
        run: hatch env run types
